# @package _global_

defaults:
  - /agent/td7
  - _self_

num_envs: 10
normalize_obs: false
discount: 0.99
total_episodes: 5000
fold_iters: 5

num_eval_envs: 16
eval_episodes: 16 # should be divided by num_eval_envs
eval_interval: 1 # unit: num of iterations

# Target update
target_update_rate: 250

rollout_episodes: 10
num_updates_per_iter: 2048
checkpoint_metric: "min"

checkpoint:
  save_interval_steps: 10


tags: ["batch1"]