# @package _global_

workflow_cls: evorl.algorithms.td7.TD7Workflow

num_envs: 10
normalize_obs: false
discount: 0.99
total_episodes: 5000
fold_iters: 1

num_eval_envs: 16
eval_episodes: 16 # should be divided by num_eval_envs
eval_interval: 10 # unit: num of iterations

random_timesteps: 25600 # steps filled into the replay buffer
learning_start_timesteps: 25600 # steps before training starts
batch_size: 256
replay_buffer_capacity: 1000000

# Target update
target_update_rate: 250

# LAP
min_priority: 1.0
lap_alpha: 0.4

exploration_epsilon: 0.1
policy_noise: 0.2
clip_policy_noise: 0.5
policy_freq: 2

optimizer:
  lr: 0.0003
  grad_clip_norm: 0 # set 0 or none to turn-off

# Checkpointing params
rollout_episodes: 10 # devided by num_envs
num_updates_per_iter: 2048 # number of gradient updates per iteration
checkpoint_metric: "min"

agent_network:
  zs_dim: 256
  zsa_dim: 256
  f_layer_sizes: [256, 256]
  g_layer_sizes: [256, 256]
  state_emb_dim: 256
  state_action_emb_dim: 256
  critic_hidden_layer_sizes: [256, 256]
  actor_hidden_layer_sizes: [256, 256]

save_replay_buffer: true
